練習課題5「Google検索結果」
codeschoolway/j-kadai-05 pull request #1
Opened 2020-03-04 23:01 UTC by codeschoolway

初回の提出: 17360cd

2020-03-05 08:43 UTC, piasoratech requested changes
コメントしたので確認をお願いします。

2020-03-05 08:43 UTC, piasoratech commented on css/style.css
> +    /* background-color: Orange; */
コメントアウトしたものはプルリクエストに含めないようにしましょう
他の箇所も同様です。

2020-03-05 08:43 UTC, piasoratech commented on index.html
> +        <footer>
`footer`タグのほうが`div`タグよりも外側にあるように修正しましょう。

2020-03-05 11:00 UTC, codeschoolway commented on css/style.css
> +    /* background-color: Orange; */
修正しました。

2020-03-05 11:03 UTC, codeschoolway commented on index.html
> +        <footer>
修正しました。

2020-03-25 03:04 UTC, nozomi71 commented on index.html
> +        </div>
h2があるブロックならsection使いたいですね

2020-03-25 04:34 UTC, codeschoolway commented on index.html
> +        </div>
HTML：
`div class="wrp"`を`section`に変更
CSS：
`.wrp`を`section`に変更

2020-03-25 06:52 UTC, nozomi71 commented on index.html
> +        </div>
ブロックで囲いましょう

2020-03-25 08:56 UTC, codeschoolway commented on index.html
> +        </div>
修正しました。何度もすみません・・・。

2020-03-26 02:41 UTC, nozomi71 commented on css/style.css
> +    margin-top: 7px;
これわざわざ指定しなくてもflex当ててるところに`justify-content`指定したら良いですね！

2020-03-26 02:41 UTC, nozomi71 commented on css/style.css
> +    margin-left: 27px;
ロゴの方で余白取りましょう

2020-03-26 02:41 UTC, nozomi71 commented on css/style.css
> +    background: rgb(26, 115, 232);
透明度変えない時は16進数で指定しましょう

2020-03-26 02:41 UTC, nozomi71 commented on css/style.css
> +    color: #ffffff;
余談ですがこれなら`#fff`でOKです

2020-03-26 02:41 UTC, nozomi71 commented on css/style.css
> +    font-size: 120%;
pxで指定しましょう

2020-03-26 02:41 UTC, nozomi71 commented on css/style.css
> +    border: 2px #eeeeee solid;
これとかも`#eee`で書けます

2020-03-26 04:59 UTC, codeschoolway commented on css/style.css
> +    margin-top: 7px;
修正しました。

2020-03-26 04:59 UTC, codeschoolway commented on css/style.css
> +    margin-left: 27px;
修正しました。

2020-03-26 04:59 UTC, codeschoolway commented on css/style.css
> +    background: rgb(26, 115, 232);
修正しました。

2020-03-26 04:59 UTC, codeschoolway commented on css/style.css
> +    color: #ffffff;
修正しました。

2020-03-26 04:59 UTC, codeschoolway commented on css/style.css
> +    font-size: 120%;
修正しました。

2020-03-26 05:00 UTC, codeschoolway commented on css/style.css
> +    border: 2px #eeeeee solid;
修正しました。

2020-03-26 05:06 UTC, codeschoolway commented on css/style.css
> +    margin-top: 7px;
`justify-content`では揃わず`align-items: flex-end`で対応しました。画像のサイズが関係しているのかも・・・。

2020-03-26 06:46 UTC, nozomi71 commented on css/style.css
> +    margin-top: 7px;
あっ単純に私のミスです、、、
`align-items`が正解です！

2020-03-26 06:51 UTC, nozomi71 commented on css/style.css
> +    padding: 11px 11px 11px 25px;
このままだとアイコンの上まで文字が入力できちゃいます

2020-03-26 06:51 UTC, nozomi71 commented on css/style.css
> +    margin: 0 0 0 auto;
```suggestion
    margin-left: auto;
```
でいいですね

2020-03-26 07:38 UTC, codeschoolway commented on css/style.css
> +    padding: 11px 11px 11px 25px;
修正しました。

2020-03-26 07:38 UTC, codeschoolway commented on css/style.css
> +    margin: 0 0 0 auto;
修正しました。

2020-03-27 04:11 UTC, umurajim approved these changes
良いかと！

2020-03-27 05:28 UTC, merged